### PR TITLE
Improve bash in glim.sh

### PR DESCRIPTION
**Pull request by nl6720**
Other planned changes rely on these commits.

### CODE REVIEW

**Comment by sebma** [comment]
@nl6720 Out of pure curiosity, I came across your [b8f21e1 commit](https://github.com/thias/glim/pull/36/commits/b8f21e1a8382cbcb14e92e9421686f47e79de936) and I really like it :+1: 

There is one bug, though :

Long options of every tool seem to work fine in your [b8f21e1 commit](https://github.com/thias/glim/pull/36/commits/b8f21e1a8382cbcb14e92e9421686f47e79de936) except for  `blkid`, which does not support long options on Ubuntu 16.04 (util-linux v2.27.1) and older (I haven't tried on Ubuntu 18.04 Bionic because I don't have it installed yet), therefore can you please revert your line : 

`USBDEV1="$(blkid --label GLIM --list-one)"`
back to : 
`USBDEV1="$(blkid -L GLIM | head -n 1)"`

**Comment by nl6720** [comment]
@sebma, I changed it to `USBDEV1="$(blkid -L GLIM -l)"`.

**Comment by sebma** [comment]
@nl6720 Great and accord to `man blkid` it can even be simplified to `USBDEV1="$(blkid -L GLIM)` because `blkid -L GLIM` equals to `blkid -l -o device -t LABEL=GLIM`

**Comment by sebma** [comment]
@nl6720 BTW : This command displays the `last device` with a `GLIM` label. If you want the first, you have to type this : 

`blkid -o device -t LABEL=GLIM | head -1`

**Comment by nl6720** [comment]
This `blkid` command improvement is only temporary. I want to remove the reliance on the "GLIM" file system label entirely: https://github.com/nl6720/glim/commit/da28deb5fa22563dfb82199b9446b3ae2152d928 .

**Pull request closed without merging**
