### PR TITLE
Check if the loop device already exists before creating one

### PR DESCRIPTION
**Pull request by slowpeek**
If grub can't start some iso, we're left with (loop) tied to that iso no matter what other item in grub menu we try to start.

Sample case (extreme one): try booting Ubuntu 10.04.4 iso. Grub will report error 'kernel too old ...' Now try any other item in grub menu and notice grub error 'device name already exists ...'

Sample case (more generic): try booting Ubuntu 14.04.6 iso. Grub will report error 'file casper/vmlinuz not found ...' Now try any other item in grub menu and notice grub error 'device name already exists ...'

The user has two options to reset the wicked state: either reboot or issue 'loopback -d loop' in grub console. It would be much more user friendly to make the problem never emerge.

---

The commit is literally the `loop` function definition and `loopback loop` replaced with `loop` everywhere in `grub2/inc-*.cfg`

### CODE REVIEW

**Comment by thias** [comment]
Thanks a lot for this! I had already thought of adding a `loopback --delete loop` inside each inc file, but I like your approach better!

**Comment by thias** [comment]
I was wondering... since I don't see glim ever requiring using more than one loop device at once, what about this instead?
```
function loop {
  loopback --delete loop
  loopback loop "$1"
}
```
And then just use:
```
loop $isofile
```
A quick test shows that the delete is silent when unconditional, so this is as simple as it would get. No major objection keeping the test to be theoretically cleaner, though.

**Comment by slowpeek** [comment]
> A quick test shows that the delete is silent when unconditional

Try running `loopback -d hmm` in grub console. It emits "error: device not found" for me. My grub is from ubuntu btw.

I like things clean so I'd like to keep the test. As for the `loop` function, yeah, it looks good. I'll push the updated branch soon

**Comment by slowpeek** [comment]
I've updated the branch

**Comment by thias** [comment]
Thanks a lot!

**Pull request merged**
