### PR TITLE
Update Manjaro & Peppermint

### PR DESCRIPTION
**Pull request by yochananmarqos**
There's a new Manjaro Architect ISO and the main editions have been updated to 18.0.2. I also updated the Peppermint entry to the latest version 9 ISO.

### CODE REVIEW

**Comment by thias** [comment]
Thanks! A few things, though:
* The multiple commits would be better squashed into one.
* The main menu Peppermint entry seems to have been lost.

I have now updated the Manjaro menu in b289862203bff0182a0f11a79d4c8c86ed54fea7 to be dynamic, so it should be easy to put any version of any variant now. I'll look into adding Peppermint properly, as it's missing the icon and could do with a dynamic menu too.

**Comment by thias** [comment]
I have now added Peppermint in 3bc6ad89b9e96cfc126396477f97adab47a771ae. Please test and let me know if I've missed anything!

**Comment by yochananmarqos** [comment]
Peppermint does not appear at all, Manjaro and SysRescueCD do not boot to desktop. Linux Mint booted, though. I'm not sure why, but I can create a new issue if you'd like.

**Comment by thias** [comment]
Peppermint not appearing at all isn't normal. It was missing from grub.cfg in your PR, but I've added it yesterday. Could you double check what set of files you're using, and maybe just re-run glim.sh from a fresh git master tree? (it won't delete and of the "iso" content on your GLIM volume)

**Comment by yochananmarqos** [comment]
I did a clean clone and Peppermint appears and boots fine. However, the same issue occurs with SystemRescueCD and Manjaro. It's odd only Debian-based distros are booting properly.

**Pull request closed without merging**
