### PR TITLE
Add support for UEFI

### PR DESCRIPTION
**Pull request by Noctiflore**
First commit adds support for UEFI (configuration and documentation).
Second commit tries to simplify grub.cfg. New version is well documented and works for me, but should be further tested.

These modification should be easy to merge with my other pending pull request.

### CODE REVIEW

**Comment by thias** [comment]
Very nice! What OS have you been testing this on? Because with Fedora, the directory has always been grub2 for me, not grub, so I'll no longer be able to copy/paste the examples... and I'm guessing that you weren't able until your changes.

**Comment by Noctiflore** [comment]
It seems to be grub on all Debian-based distributions (tested on Debian and Linux Mint).
Maybe because Debian marked Grub legacy and Grub 2 as conflicting, so that they can't be installed both (I don't know whether it's possible in Fedora…).

**Comment by mikeodr** [comment]
I just re-installed to a new USB key I received last night.

On ubuntu the command is `grub-install` and the directory is `grub` and not `grub2`. I think the `README.md` should have both examples

**Comment by mikeodr** [comment]
Also @Noctiflore thanks for adding this, it was going to be my next PR into this project when I found some time.

**Comment by thias** [comment]
Thanks again so so much for this! Sorry for such a long delay...

I have adapted the EFI changes in 393e61d016c1d3220e3833dd34cb0d09575e097a and c008da2ac75318f1d85d330074072e1321c58a1c.

**Pull request closed without merging**
